---
- name: Install Kind Cluster
  hosts: localhost
  vars:
    orc8r_domain: "magma.local"
    deploy_on_kind: true

  roles:
    - role: create
    - role: shubhamtatvamasi.magma.metallb
    # - role: delete
