---
- name: Check if Kind Cluster is running
  command: kind get clusters
  register: kind_cluster_running

- name: Create Kind Cluster on macOS
  when: ( ansible_distribution == "MacOSX" ) and ( kind_cluster_running.stdout != "kind" )
  shell: |
    kind create cluster --config - << EOF
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
      extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
    EOF
