---
- name: Check if Kind Cluster is running
  command: kind get clusters
  register: kind_cluster_running

- name: Create Kind Cluster on macOS
  when: not "orc8r" in kind_cluster_running.stdout
  shell: |
    kind create cluster --name orc8r --config - << EOF
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
      extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
    EOF

- name: Set {{ magma_namespace }} as default namespace
  command: kubectl config set-context --current --namespace {{ magma_namespace }}
