---
- name: Check if Kind Cluster is running
  command: kind get clusters
  register: kind_cluster_running

- name: Create Kind Cluster
  when: kind_cluster_running.stdout != "kind"
  shell: |
    kind create cluster --config - << EOF
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
      extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
    EOF

- name: Get node info
  kubernetes.core.k8s_info:
    kind: Node
  register: node_info

- name: Set MetallLB IP
  set_fact:
    metallb_ip: "{{ node_info.resources[0].status.addresses[0].address }}"

- name: Install MetallLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    chart_version: "{{ metallb_chart_version }}"
    create_namespace: true
    values:
      configInline:
        address-pools:
          - name: default
            protocol: layer2
            addresses:
              - "{{ metallb_ip }}/32"
